Repository ashut0sh75/Cartoon, pull requests merged in 2023-10, with the labels that each got.

#5 Updated splash screen
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/cartoon/Sp_screen.kt
  app/src/main/res/drawable/imgm.png
  app/src/main/res/layout/activity_sp_screen.xml
  app/src/main/res/values/colors.xml
Labels: Hacktoberfest, Hacktoberfest accepted

#19 Notification Update
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/cartoon/MainActivity.kt
  app/src/main/java/com/example/cartoon/Notification.kt
  app/src/main/res/drawable/baseline_notifications_24.xml
Labels: Hacktoberfest, Hacktoberfest accepted

#21 Updated README.md
  README.md
Labels: Hacktoberfest, Hacktoberfest accepted

#24 Adds github workflow actions
  .github/workflows/gradle-wrapper-validation.yml
  .github/workflows/pre-merge.yaml
  gradlew
Labels: enhancement

#29 locked the activities in portrait mode🥷🥷
  app/src/main/AndroidManifest.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/themes.xml
Labels: bug, good first issue, Hacktoberfest, Hacktoberfest accepted

#31 fixed the notification issue
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/cartoon/MainActivity.kt
  app/src/main/java/com/example/cartoon/Notification.kt
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: waiting for review

#35 updated the ui🥷🥷🥷
  app/src/main/java/com/example/cartoon/MainActivity.kt
  app/src/main/java/com/example/cartoon/Sp_screen.kt
  app/src/main/res/drawable/btn_bg.xml
  app/src/main/res/drawable/convert.png
  app/src/main/res/font/pixelfont.ttf
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_sp_screen.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/custom_image_view.xml
Labels: enhancement, good first issue, Hacktoberfest, Hacktoberfest accepted

#37 Implemented viewBinding
  app/build.gradle
  app/src/main/java/com/example/cartoon/MainActivity.kt
  app/src/main/java/com/example/cartoon/Sp_screen.kt
  app/src/main/res/layout/activity_sp_screen.xml
Labels: enhancement, good first issue, Hacktoberfest, Hacktoberfest accepted

#40 #34 code cleanup
  app/src/main/java/com/example/cartoon/MainActivity.kt
  app/src/main/java/com/example/cartoon/Notification.kt
  app/src/main/java/com/example/cartoon/Sp_screen.kt
  app/src/main/java/com/example/cartoon/utils/Helpers.kt
  app/src/main/java/com/example/cartoon/utils/ToastUtils.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_sp_screen.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, Hacktoberfest, Hacktoberfest accepted
